import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import WeatherCard from '../componets/WeatherCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>pages/index.tsx</code>
            </p>
          </div>
        </div>
        <div className={styles.center}>
          <WeatherCard />
        </div>
        <div className={styles.center}>
          <a
            href="https://openweathermap.org/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              OpenWeather <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Weather forecasts, nowcasts and history in a fast and elegant way
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
